# Contains the level root folders for all likely users

Q_ROOT = 'C:\Users\qtran\Desktop\PROJECT Whale Nebula\WhaleNebula\Assets\StreamingAssets\levels\'
Q_PATTERN = 'C:\Users\qtran\Desktop\Github Projects\StarTools\input\patterns\'

T_ROOT = 'C:\Insert your file path here'
T_PATTERN = 'C:\Insert your file path here'
